### ISSUE TITLE
请问如果使用自己的feature-imitation方法应该在哪里添加，您的feature-imitation代码写在哪里了，我没有找到

### ISSUE THREAD

**Issue by yg333** [HikariTJU/LD#60]

**Comment by HikariTJU** [comment]
计算imitation区域的在 https://github.com/HikariTJU/LD/blob/bc60bbcd48e9305e61e32a0d2c981621e2ae0d05/mmdet/models/dense_heads/ld_head.py#L580

计算loss的在
https://github.com/HikariTJU/LD/blob/bc60bbcd48e9305e61e32a0d2c981621e2ae0d05/mmdet/models/dense_heads/ld_head.py#L170

**Comment by yg333** [comment]
请问我的环境都是对的 但是您的源码训练就报错，弄了好几天，实在没辙了

**Comment by yg333** [comment]
@HikariTJU 
File "/media/lj/CAD2B4B7D2B4A959/students/yg/LD-main/mmdet/models/detectors/kd_one_stage.py", line 34, in __init__
  File "/media/lj/CAD2B4B7D2B4A959/students/yg/LD-main/mmdet/models/detectors/kd_one_stage.py", line 34, in __init__
    return build_from_cfg(cfg, registry, default_args)
  File "/home/lj/anaconda3/envs/mmlab/lib/python3.8/site-packages/mmcv/utils/registry.py", line 171, in build_from_cfg
    return obj_cls(**args)
  File "/media/lj/CAD2B4B7D2B4A959/students/yg/LD-main/mmdet/models/detectors/kd_one_stage.py", line 34, in __init__
    super().__init__(backbone, neck, bbox_head, train_cfg, test_cfg,
  File "/media/lj/CAD2B4B7D2B4A959/students/yg/LD-main/mmdet/models/detectors/single_stage.py", line 33, in __init__
    super().__init__(backbone, neck, bbox_head, train_cfg, test_cfg,
  File "/media/lj/CAD2B4B7D2B4A959/students/yg/LD-main/mmdet/models/detectors/single_stage.py", line 33, in __init__
    super().__init__(backbone, neck, bbox_head, train_cfg, test_cfg,
          File "/media/lj/CAD2B4B7D2B4A959/students/yg/LD-main/mmdet/models/detectors/single_stage.py", line 33, in __init__
super().__init__(backbone, neck, bbox_head, train_cfg, test_cfg,super().__init__(backbone, neck, bbox_head, train_cfg, test_cfg,

  File "/media/lj/CAD2B4B7D2B4A959/students/yg/LD-main/mmdet/models/detectors/single_stage.py", line 33, in __init__
  File "/media/lj/CAD2B4B7D2B4A959/students/yg/LD-main/mmdet/models/detectors/single_stage.py", line 33, in __init__
    super().__init__(backbone, neck, bbox_head, train_cfg, test_cfg,
    super().__init__(backbone, neck, bbox_head, train_cfg, test_cfg,  File "/media/lj/CAD2B4B7D2B4A959/students/yg/LD-main/mmdet/models/detectors/single_stage.py", line 33, in __init__

  File "/media/lj/CAD2B4B7D2B4A959/students/yg/LD-main/mmdet/models/detectors/single_stage.py", line 33, in __init__
    super().__init__(backbone, neck, bbox_head, train_cfg, test_cfg,
  File "/media/lj/CAD2B4B7D2B4A959/students/yg/LD-main/mmdet/models/detectors/single_stage.py", line 33, in __init__
            self.init_weights(pretrained=pretrained)self.init_weights(pretrained=pretrained)self.init_weights(pretrained=pretrained)


      File "/media/lj/CAD2B4B7D2B4A959/students/yg/LD-main/mmdet/models/detectors/single_stage.py", line 43, in init_weights
  File "/media/lj/CAD2B4B7D2B4A959/students/yg/LD-main/mmdet/models/detectors/single_stage.py", line 43, in init_weights
  File "/media/lj/CAD2B4B7D2B4A959/students/yg/LD-main/mmdet/models/detectors/single_stage.py", line 43, in init_weights
self.init_weights(pretrained=pretrained)    
self.init_weights(pretrained=pretrained)
  File "/media/lj/CAD2B4B7D2B4A959/students/yg/LD-main/mmdet/models/detectors/single_stage.py", line 43, in init_weights
  File "/media/lj/CAD2B4B7D2B4A959/students/yg/LD-main/mmdet/models/detectors/single_stage.py", line 43, in init_weights
    self.init_weights(pretrained=pretrained)
      File "/media/lj/CAD2B4B7D2B4A959/students/yg/LD-main/mmdet/models/detectors/single_stage.py", line 43, in init_weights
self.init_weights(pretrained=pretrained)
  File "/media/lj/CAD2B4B7D2B4A959/students/yg/LD-main/mmdet/models/detectors/single_stage.py", line 43, in init_weights
    self.init_weights(pretrained=pretrained)
  File "/media/lj/CAD2B4B7D2B4A959/students/yg/LD-main/mmdet/models/detectors/single_stage.py", line 43, in init_weights
    self.backbone.init_weights(pretrained=pretrained)
    self.backbone.init_weights(pretrained=pretrained)  File "/media/lj/CAD2B4B7D2B4A959/students/yg/LD-main/mmdet/models/backbones/resnet.py", line 599, in init_weights

      File "/media/lj/CAD2B4B7D2B4A959/students/yg/LD-main/mmdet/models/backbones/resnet.py", line 599, in init_weights
    self.backbone.init_weights(pretrained=pretrained)self.backbone.init_weights(pretrained=pretrained)
    
self.backbone.init_weights(pretrained=pretrained)  File "/media/lj/CAD2B4B7D2B4A959/students/yg/LD-main/mmdet/models/backbones/resnet.py", line 599, in init_weights

  File "/media/lj/CAD2B4B7D2B4A959/students/yg/LD-main/mmdet/models/backbones/resnet.py", line 599, in init_weights
  File "/media/lj/CAD2B4B7D2B4A959/students/yg/LD-main/mmdet/models/backbones/resnet.py", line 599, in init_weights
        self.backbone.init_weights(pretrained=pretrained)self.backbone.init_weights(pretrained=pretrained)

  File "/media/lj/CAD2B4B7D2B4A959/students/yg/LD-main/mmdet/models/backbones/resnet.py", line 599, in init_weights
  File "/media/lj/CAD2B4B7D2B4A959/students/yg/LD-main/mmdet/models/backbones/resnet.py", line 599, in init_weights
    self.backbone.init_weights(pretrained=pretrained)
  File "/media/lj/CAD2B4B7D2B4A959/students/yg/LD-main/mmdet/models/backbones/resnet.py", line 599, in init_weights
    load_checkpoint(self, pretrained, strict=False, logger=logger)
  File "/home/lj/anaconda3/envs/mmlab/lib/python3.8/site-packages/mmcv/runner/checkpoint.py", line 279, in load_checkpoint
    load_checkpoint(self, pretrained, strict=False, logger=logger)
  File "/home/lj/anaconda3/envs/mmlab/lib/python3.8/site-packages/mmcv/runner/checkpoint.py", line 279, in load_checkpoint
    load_checkpoint(self, pretrained, strict=False, logger=logger)
      File "/home/lj/anaconda3/envs/mmlab/lib/python3.8/site-packages/mmcv/runner/checkpoint.py", line 279, in load_checkpoint
load_checkpoint(self, pretrained, strict=False, logger=logger)
      File "/home/lj/anaconda3/envs/mmlab/lib/python3.8/site-packages/mmcv/runner/checkpoint.py", line 279, in load_checkpoint
load_checkpoint(self, pretrained, strict=False, logger=logger)    
load_checkpoint(self, pretrained, strict=False, logger=logger)
  File "/home/lj/anaconda3/envs/mmlab/lib/python3.8/site-packages/mmcv/runner/checkpoint.py", line 279, in load_checkpoint
  File "/home/lj/anaconda3/envs/mmlab/lib/python3.8/site-packages/mmcv/runner/checkpoint.py", line 279, in load_checkpoint
    checkpoint = _load_checkpoint(filename, map_location)
      File "/home/lj/anaconda3/envs/mmlab/lib/python3.8/site-packages/mmcv/runner/checkpoint.py", line 224, in _load_checkpoint
load_checkpoint(self, pretrained, strict=False, logger=logger)
  File "/home/lj/anaconda3/envs/mmlab/lib/python3.8/site-packages/mmcv/runner/checkpoint.py", line 279, in load_checkpoint
    checkpoint = _load_checkpoint(filename, map_location)
  File "/home/lj/anaconda3/envs/mmlab/lib/python3.8/site-packages/mmcv/runner/checkpoint.py", line 224, in _load_checkpoint
            checkpoint = _load_checkpoint(filename, map_location)checkpoint = load_url_dist(model_urls[model_name])load_checkpoint(self, pretrained, strict=False, logger=logger)


  File "/home/lj/anaconda3/envs/mmlab/lib/python3.8/site-packages/mmcv/runner/checkpoint.py", line 114, in load_url_dist
  File "/home/lj/anaconda3/envs/mmlab/lib/python3.8/site-packages/mmcv/runner/checkpoint.py", line 224, in _load_checkpoint
  File "/home/lj/anaconda3/envs/mmlab/lib/python3.8/site-packages/mmcv/runner/checkpoint.py", line 279, in load_checkpoint
    checkpoint = _load_checkpoint(filename, map_location)
  File "/home/lj/anaconda3/envs/mmlab/lib/python3.8/site-packages/mmcv/runner/checkpoint.py", line 224, in _load_checkpoint
        checkpoint = _load_checkpoint(filename, map_location)checkpoint = _load_checkpoint(filename, map_location)

      File "/home/lj/anaconda3/envs/mmlab/lib/python3.8/site-packages/mmcv/runner/checkpoint.py", line 224, in _load_checkpoint
  File "/home/lj/anaconda3/envs/mmlab/lib/python3.8/site-packages/mmcv/runner/checkpoint.py", line 224, in _load_checkpoint
checkpoint = load_url_dist(model_urls[model_name])
          File "/home/lj/anaconda3/envs/mmlab/lib/python3.8/site-packages/mmcv/runner/checkpoint.py", line 114, in load_url_dist
checkpoint = _load_checkpoint(filename, map_location)    torch.distributed.barrier()
checkpoint = load_url_dist(model_urls[model_name])

  File "/home/lj/anaconda3/envs/mmlab/lib/python3.8/site-packages/mmcv/runner/checkpoint.py", line 224, in _load_checkpoint
  File "/home/lj/anaconda3/envs/mmlab/lib/python3.8/site-packages/mmcv/runner/checkpoint.py", line 114, in load_url_dist
  File "/home/lj/anaconda3/envs/mmlab/lib/python3.8/site-packages/torch/distributed/distributed_c10d.py", line 2420, in barrier
    checkpoint = load_url_dist(model_urls[model_name])
  File "/home/lj/anaconda3/envs/mmlab/lib/python3.8/site-packages/mmcv/runner/checkpoint.py", line 114, in load_url_dist
    checkpoint = _load_checkpoint(filename, map_location)
    torch.distributed.barrier()  File "/home/lj/anaconda3/envs/mmlab/lib/python3.8/site-packages/mmcv/runner/checkpoint.py", line 224, in _load_checkpoint

      File "/home/lj/anaconda3/envs/mmlab/lib/python3.8/site-packages/torch/distributed/distributed_c10d.py", line 2420, in barrier
torch.distributed.barrier()        
checkpoint = load_url_dist(model_urls[model_name])checkpoint = load_url_dist(model_urls[model_name])
  File "/home/lj/anaconda3/envs/mmlab/lib/python3.8/site-packages/torch/distributed/distributed_c10d.py", line 2420, in barrier

  File "/home/lj/anaconda3/envs/mmlab/lib/python3.8/site-packages/mmcv/runner/checkpoint.py", line 114, in load_url_dist
  File "/home/lj/anaconda3/envs/mmlab/lib/python3.8/site-packages/mmcv/runner/checkpoint.py", line 114, in load_url_dist
    torch.distributed.barrier()    
checkpoint = load_url_dist(model_urls[model_name])  File "/home/lj/anaconda3/envs/mmlab/lib/python3.8/site-packages/torch/distributed/distributed_c10d.py", line 2420, in barrier

  File "/home/lj/anaconda3/envs/mmlab/lib/python3.8/site-packages/mmcv/runner/checkpoint.py", line 114, in load_url_dist
    checkpoint = load_url_dist(model_urls[model_name])
          File "/home/lj/anaconda3/envs/mmlab/lib/python3.8/site-packages/mmcv/runner/checkpoint.py", line 114, in load_url_dist
torch.distributed.barrier()torch.distributed.barrier()

  File "/home/lj/anaconda3/envs/mmlab/lib/python3.8/site-packages/torch/distributed/distributed_c10d.py", line 2420, in barrier
  File "/home/lj/anaconda3/envs/mmlab/lib/python3.8/site-packages/torch/distributed/distributed_c10d.py", line 2420, in barrier
    torch.distributed.barrier()
  File "/home/lj/anaconda3/envs/mmlab/lib/python3.8/site-packages/torch/distributed/distributed_c10d.py", line 2420, in barrier
    torch.distributed.barrier()
  File "/home/lj/anaconda3/envs/mmlab/lib/python3.8/site-packages/torch/distributed/distributed_c10d.py", line 2420, in barrier
    work = default_pg.barrier(opts=opts)
RuntimeError: NCCL error in: /opt/conda/conda-bld/pytorch_1614378083779/work/torch/lib/c10d/ProcessGroupNCCL.cpp:825, invalid usage, NCCL version 2.7.8
ncclInvalidUsage: This usually reflects invalid usage of NCCL library (such as too many async ops, too many collectives at once, mixing streams in a group, etc).
    work = default_pg.barrier(opts=opts)
RuntimeError: NCCL error in: /opt/conda/conda-bld/pytorch_1614378083779/work/torch/lib/c10d/ProcessGroupNCCL.cpp:825, invalid usage, NCCL version 2.7.8
ncclInvalidUsage: This usually reflects invalid usage of NCCL library (such as too many async ops, too many collectives at once, mixing streams in a group, etc).
    work = default_pg.barrier(opts=opts)
RuntimeError: NCCL error in: /opt/conda/conda-bld/pytorch_1614378083779/work/torch/lib/c10d/ProcessGroupNCCL.cpp:825, invalid usage, NCCL version 2.7.8
ncclInvalidUsage: This usually reflects invalid usage of NCCL library (such as too many async ops, too many collectives at once, mixing streams in a group, etc).
    work = default_pg.barrier(opts=opts)
RuntimeError: NCCL error in: /opt/conda/conda-bld/pytorch_1614378083779/work/torch/lib/c10d/ProcessGroupNCCL.cpp:825, invalid usage, NCCL version 2.7.8
ncclInvalidUsage: This usually reflects invalid usage of NCCL library (such as too many async ops, too many collectives at once, mixing streams in a group, etc).
            work = default_pg.barrier(opts=opts)work = default_pg.barrier(opts=opts)work = default_pg.barrier(opts=opts)


RuntimeErrorRuntimeErrorRuntimeError: : : NCCL error in: /opt/conda/conda-bld/pytorch_1614378083779/work/torch/lib/c10d/ProcessGroupNCCL.cpp:825, invalid usage, NCCL version 2.7.8
ncclInvalidUsage: This usually reflects invalid usage of NCCL library (such as too many async ops, too many collectives at once, mixing streams in a group, etc).NCCL error in: /opt/conda/conda-bld/pytorch_1614378083779/work/torch/lib/c10d/ProcessGroupNCCL.cpp:825, invalid usage, NCCL version 2.7.8
ncclInvalidUsage: This usually reflects invalid usage of NCCL library (such as too many async ops, too many collectives at once, mixing streams in a group, etc).NCCL error in: /opt/conda/conda-bld/pytorch_1614378083779/work/torch/lib/c10d/ProcessGroupNCCL.cpp:825, invalid usage, NCCL version 2.7.8
ncclInvalidUsage: This usually reflects invalid usage of NCCL library (such as too many async ops, too many collectives at once, mixing streams in a group, etc).


    work = default_pg.barrier(opts=opts)
RuntimeError: NCCL error in: /opt/conda/conda-bld/pytorch_1614378083779/work/torch/lib/c10d/ProcessGroupNCCL.cpp:825, invalid usage, NCCL version 2.7.8
ncclInvalidUsage: This usually reflects invalid usage of NCCL library (such as too many async ops, too many collectives at once, mixing streams in a group, etc).
Killing subprocess 1548
Killing subprocess 1550
Killing subprocess 1552
Killing subprocess 1555
Killing subprocess 1563
Killing subprocess 1564
Killing subprocess 1566
Killing subprocess 1567
Traceback (most recent call last):
  File "/home/lj/anaconda3/envs/mmlab/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/lj/anaconda3/envs/mmlab/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/lj/anaconda3/envs/mmlab/lib/python3.8/site-packages/torch/distributed/launch.py", line 340, in <module>
    main()
  File "/home/lj/anaconda3/envs/mmlab/lib/python3.8/site-packages/torch/distributed/launch.py", line 326, in main
    sigkill_handler(signal.SIGTERM, None)  # not coming back
  File "/home/lj/anaconda3/envs/mmlab/lib/python3.8/site-packages/torch/distributed/launch.py", line 301, in sigkill_handler
    raise subprocess.CalledProcessError(returncode=last_return_code, cmd=cmd)
subprocess.CalledProcessError: Command '['/home/lj/anaconda3/envs/mmlab/bin/python', '-u', 'tools/train.py', '--local_rank=7', 'configs/ld/ld_retina_r50_1x.py', '--launcher', 'pytorch']' returned non-zero exit status 1.

**Comment by HikariTJU** [comment]
请使用标准模板报告bug， 我推荐你可以先试一下单卡能不能跑

`python tools/train.py ${config}`



以下是标准模板

**Checklist**
1. I have searched related issues but cannot get the expected help.
2. The bug has not been fixed in the latest version.

**Describe the bug**
A clear and concise description of what the bug is.

**Reproduction**
1. What command or script did you run?
```
A placeholder for the command.
```
2. Did you make any modifications on the code or config? Did you understand what you have modified?
3. What dataset did you use?

**Environment**

1. Please run `python mmdet/utils/collect_env.py` to collect necessary environment information and paste it here.
2. You may add addition that may be helpful for locating the problem, such as
    - How you installed PyTorch [e.g., pip, conda, source]
    - Other environment variables that may be related (such as `$PATH`, `$LD_LIBRARY_PATH`, `$PYTHONPATH`, etc.)

**Error traceback**
If applicable, paste the error trackback here.
```
A placeholder for trackback.
```

**Bug fix**
If you have already identified the reason, you can provide the information here. If you are willing to create a PR to fix it, please also leave a comment here and that would be much appreciated!

**Comment by yg333** [comment]
谢谢您，单卡训练就可以了。还有个问题我没搞清楚。比如我想用Masked Generative Distillation论文的特征图蒸馏方法。我只需要改这段代码就可以了吗？谢谢您的及时回复
` if self.imitation_method == 'gibox':
            gi_idx = self.get_gi_region(soft_label, cls_score, anchors,
                                        bbox_pred, soft_targets, stride)
            gi_teacher = teacher_x[gi_idx]
            gi_student = x[gi_idx]

            loss_im = self.loss_im(gi_student, gi_teacher)`

**Comment by yg333** [comment]
谢谢您，单卡训练就可以了。还有个问题我没搞清楚。比如我想用Masked Generative Distillation论文的特征图蒸馏方法。我只需要改这段代码就可以了吗？谢谢您的及时回复
`if self.imitation_method == 'gibox':`
`gi_idx = self.get_gi_region(soft_label, cls_score, anchors,
                                        bbox_pred, soft_targets, stride)`
`gi_teacher = teacher_x[gi_idx]`
`gi_student = x[gi_idx]`
`loss_im = self.loss_im(gi_student, gi_teacher)`

**Comment by HikariTJU** [comment]
1. 单卡能跑多卡不能跑说明，你可能多卡的launch命令错了
